version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: nest-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: yg
      POSTGRES_PASSWORD: yg1234
      POSTGRES_DB: yg
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
